image: docker:stable

services:
  - docker:stable-dind

stages:
  - version-5
  - version-6

variables:
  IMAGE_NAME: bs-platform

bs-platform-v5:
  stage: version-5
  variables:
    VERSION: "5.2.1"
  script:
    - docker build . --no-cache --pull
      -t $DOCKER_USER/$IMAGE_NAME:$VERSION
      -t $DOCKER_USER/$IMAGE_NAME:$VERSION-alpine
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg CI_JOB_ID=$CI_JOB_ID
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_USER/$IMAGE_NAME:$VERSION-alpine
    - docker push $DOCKER_USER/$IMAGE_NAME:$VERSION
  only:
    - master

bs-platform-v6:
  stage: version-6
  variables:
    VERSION: "6.2.1"
  script:
    - docker build . --no-cache --pull
      -t $DOCKER_USER/$IMAGE_NAME:$VERSION
      -t $DOCKER_USER/$IMAGE_NAME:$VERSION-alpine
      -t $DOCKER_USER/$IMAGE_NAME:latest
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg CI_JOB_ID=$CI_JOB_ID
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_USER/$IMAGE_NAME:$VERSION-alpine
    - docker push $DOCKER_USER/$IMAGE_NAME:$VERSION
    - docker push $DOCKER_USER/$IMAGE_NAME:latest
  only:
    - master
